version: '3'
services:
  server:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    volumes:
      - ./postgrest.conf:/etc/postgrest.conf:Z
    depends_on:
      - db
  db:
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${pg_db}
      POSTGRES_USER: ${pg_user}
      POSTGRES_PASSWORD: ${pg_pwd}
    volumes:
      - data:/var/lib/postgresql/data
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "3001:8080"
    expose:
      - "3001"
    environment:
      API_URL: ${base_uri}/api
volumes:
  data:
