FROM nginx:stable-alpine

COPY ./nginx-site.template /etc/nginx/conf.d/mysite.template
COPY ./webroot /var/www/html
CMD /bin/sh -c "envsubst '\$PHP_HOST \$API_HOST' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
