version: '3'
services:
  api:
    restart: always
    image: postgrest/postgrest
    volumes:
      - ./postgrest.conf:/etc/postgrest.conf:Z
    depends_on:
      - db
  db:
    restart: always
    image: postgres:12
    environment:
      POSTGRES_DB: ${db_name}
      POSTGRES_USER: ${db_root_user}
      POSTGRES_PASSWORD: ${db_root_pass}
    volumes:
      - db-data:/var/lib/postgresql/data
  php:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-for-php
    volumes:
      - ../webroot/:/var/www/html:z
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${db_name}
      DB_USER: ${db_auth_user}
      DB_PASS: ${db_auth_pass}
      JWT_SECRET: ${jwt_secret}
  nginx:
    restart: always
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
      - php
    volumes:
      - ./nginx-site.conf:/etc/nginx/conf.d/default.conf:Z
      - ../webroot:/var/www/html:z
volumes:
  db-data:
